name: template_parser
description: A dart package to parse String template. It's a secure template language that is also very accessible for programmer audiences.
version: 0.0.2
homepage: https://github.com/sodipto/flutter-template-parser

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:

dev_dependencies: